services:
  database:
    image: mysql:9.7.1
    container_name: ctf-database
    environment:
      MYSQL_DATABASE: code-task-follower
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 1s
      timeout: 3s
      retries: 20
      start_period: 5s
    ports:
      - ":3306"
    volumes:
      - database-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    networks:
      - ctf-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf-backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      - ctf-network

  frontend:
    build:
      context: ../code-task-follower-frontend
      dockerfile: Dockerfile
    container_name: ctf-frontend
    ports:
      - "80:80"
    networks:
      - ctf-network

volumes:
  database-data:

networks:
  ctf-network:
    driver: bridge